/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar for docs and notes
  docsSidebar: [
    'intro', // Directly include intro without wrapping in a "Documentation" category
    {
      type: 'category',
      label: 'Notes', // Dedicated section for notes
      items: [
        {
          type: 'autogenerated',
          dirName: 'notes', // Autogenerate sidebar for all files in docs/notes folder
        },
      ],
    },
  ],
};

module.exports = sidebars;